sudo: required

language: ruby

services:
  - docker

script:
  - docker build -t vguar/2i-base-alpine  .

after_success:
  -  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  -  docker push vguar/s2i-base-alpine
